version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
  npm-test:
    docker:
      -image: circleci/node:8
    steps:
      - checkout
      - run:
        name: Test
        command: npm test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - npm-test
      - cypress/run:
        record: true
